// Generated by scripts/gen-salla-ids.mjs from docs/build/salla-ids.json.
// Do not edit by hand: run `pnpm gen:salla-ids` after a store write instead.
//
// 47 products created on the live store, 38 with a photo
// attached. `path` is the store's own SEO slug and already carries the
// `/p<id>` suffix the product route matches; the engine `Link` adds the locale
// segment. `type` is set only where the API created a non-default product type
// (digital, service); `booking` items were created as `service` and the owner
// converts them in the dashboard (PLAN-final C14).

export interface SallaProductRef {
  /** The catalogue SKU from FINAL-catalogue.md. */
  id: number;
  /** Path on the store, e.g. `/<slug>/p<id>`. */
  path: string;
  /** A photo is attached; the rest wait for owner artwork. */
  hasImage: boolean;
  /** `digital`, `service`, or null for a plain product. */
  type: string | null;
}

export const SALLA_IDS = {
  "OX-001": { id: 1996831868, path: "/p1996831868", hasImage: false, type: null },
  "OX-002": { id: 1057022406, path: "/نيترو-تك-واي-جولد-227-كجم-من-مسل-تك-اوبتيمال-اكس/p1057022406", hasImage: true, type: null },
  "OX-003": { id: 8232454, path: "/p8232454", hasImage: true, type: null },
  "OX-004": { id: 290277404, path: "/p290277404", hasImage: true, type: null },
  "OX-005": { id: 1663719197, path: "/p1663719197", hasImage: true, type: null },
  "OX-006": { id: 1488630808, path: "/p1488630808", hasImage: true, type: null },
  "OX-007": { id: 74248730, path: "/p74248730", hasImage: true, type: null },
  "OX-008": { id: 1339588198, path: "/p1339588198", hasImage: true, type: null },
  "OX-009": { id: 1193355662, path: "/p1193355662", hasImage: false, type: null },
  "OX-010": { id: 214189933, path: "/p214189933", hasImage: true, type: null },
  "OX-011": { id: 680494447, path: "/p680494447", hasImage: true, type: null },
  "OX-012": { id: 2052367464, path: "/p2052367464", hasImage: true, type: null },
  "OX-013": { id: 1412547433, path: "/p1412547433", hasImage: true, type: null },
  "OX-014": { id: 1945829739, path: "/p1945829739", hasImage: true, type: null },
  "OX-015": { id: 995134839, path: "/p995134839", hasImage: true, type: null },
  "OX-016": { id: 779499389, path: "/p779499389", hasImage: true, type: null },
  "OX-017": { id: 1836761674, path: "/p1836761674", hasImage: true, type: null },
  "OX-018": { id: 153878612, path: "/p153878612", hasImage: true, type: null },
  "OX-019": { id: 1527328597, path: "/p1527328597", hasImage: true, type: null },
  "OX-020": { id: 886459990, path: "/p886459990", hasImage: true, type: null },
  "OX-021": { id: 577153873, path: "/p577153873", hasImage: true, type: null },
  "OX-022": { id: 684106154, path: "/p684106154", hasImage: true, type: null },
  "OX-023": { id: 2057552043, path: "/p2057552043", hasImage: true, type: null },
  "OX-024": { id: 643108533, path: "/p643108533", hasImage: true, type: null },
  "OX-025": { id: 1882336694, path: "/p1882336694", hasImage: true, type: null },
  "OX-026": { id: 535063472, path: "/p535063472", hasImage: true, type: null },
  "OX-027": { id: 1001367986, path: "/p1001367986", hasImage: true, type: null },
  "OX-028": { id: 1390995085, path: "/p1390995085", hasImage: true, type: null },
  "OX-029": { id: 1659590536, path: "/p1659590536", hasImage: false, type: null },
  "OX-030": { id: 750060942, path: "/p750060942", hasImage: true, type: null },
  "OX-031": { id: 1216299912, path: "/p1216299912", hasImage: true, type: null },
  "OX-032": { id: 1175429259, path: "/p1175429259", hasImage: true, type: null },
  "OX-033": { id: 159067287, path: "/p159067287", hasImage: true, type: null },
  "OX-034": { id: 892168849, path: "/p892168849", hasImage: true, type: null },
  "OX-035": { id: 299069850, path: "/p299069850", hasImage: true, type: null },
  "OX-036": { id: 1673105563, path: "/p1673105563", hasImage: true, type: null },
  "OX-037": { id: 1497955814, path: "/p1497955814", hasImage: true, type: null },
  "OX-038": { id: 82983904, path: "/p82983904", hasImage: true, type: null },
  "OX-039": { id: 547650018, path: "/p547650018", hasImage: true, type: null },
  "OX-040": { id: 1746003438, path: "/p1746003438", hasImage: true, type: null },
  "OX-041": { id: 1141798217, path: "/p1141798217", hasImage: true, type: null },
  "OX-042": { id: 702549495, path: "/p702549495", hasImage: false, type: "digital" },
  "OX-043": { id: 662137586, path: "/p662137586", hasImage: false, type: "codes" },
  "OX-044": { id: 487045117, path: "/p487045117", hasImage: false, type: "service" },
  "OX-045": { id: 2000960449, path: "/p2000960449", hasImage: false, type: "service (booking_details required by API; convert in dashboard)" },
  "OX-046": { id: 1051830221, path: "/p1051830221", hasImage: false, type: "service (convert to booking in dashboard)" },
  "OX-047": { id: 103621577, path: "/p103621577", hasImage: false, type: "service (convert to booking in dashboard)" },
} as const satisfies Record<string, SallaProductRef>;

export type SallaSku = keyof typeof SALLA_IDS;

/** The product id for a SKU, or undefined when the SKU is not in the map. */
export function idForSku(sku: string): number | undefined {
  return (SALLA_IDS as Record<string, SallaProductRef>)[sku]?.id;
}

/** The store path for a SKU, or undefined when the SKU is not in the map. */
export function pathForSku(sku: string): string | undefined {
  return (SALLA_IDS as Record<string, SallaProductRef>)[sku]?.path;
}

/** Every id in the map, in SKU order: the "latest products" fallback list. */
export const SALLA_PRODUCT_IDS: number[] = Object.values(
  SALLA_IDS as Record<string, SallaProductRef>
).map((entry) => entry.id);
