/**
 * The owner's photographs of the Al Khalidiyah branch (owner brief 2026-09-24),
 * GENERATED by scripts/store-photos-import.mjs. Do not edit by hand; rerun
 * the script with the owner's folder.
 *
 * `widths` lists the renditions that exist on disk, smallest first, the last
 * one being the file at `photo`. Nothing is upscaled: a surface builds its
 * `srcset` from this list, never from a width table of its own, so a small
 * original (the storefront is 415px wide) is served sharp at its own size
 * rather than blurred up to a slot it cannot fill.
 */
export interface StorePhoto {
  /** The largest rendition, under public/. */
  photo: string;
  width: number;
  height: number;
  /** Renditions on disk, ascending; `photo` is the last. */
  widths: readonly number[];
}

export type StorePhotoSlug = 'storefront' | 'shelves' | 'store-wide' | 'advisory-room' | 'waiting-area';

export const STORE_PHOTOS: Record<StorePhotoSlug, StorePhoto> = {
  'storefront': {
    /** The largest rendition; `<slug>-{w}.webp` at every other width. */
    photo: '/assets/store/storefront.webp',
    width: 415,
    height: 241,
    widths: [380, 415],
  },
  'shelves': {
    /** The largest rendition; `<slug>-{w}.webp` at every other width. */
    photo: '/assets/store/shelves.webp',
    width: 512,
    height: 537,
    widths: [380, 480, 512],
  },
  'store-wide': {
    /** The largest rendition; `<slug>-{w}.webp` at every other width. */
    photo: '/assets/store/store-wide.webp',
    width: 1139,
    height: 1093,
    widths: [380, 480, 760, 1139],
  },
  'advisory-room': {
    /** The largest rendition; `<slug>-{w}.webp` at every other width. */
    photo: '/assets/store/advisory-room.webp',
    width: 497,
    height: 722,
    widths: [380, 480, 497],
  },
  'waiting-area': {
    /** The largest rendition; `<slug>-{w}.webp` at every other width. */
    photo: '/assets/store/waiting-area.webp',
    width: 1482,
    height: 1061,
    widths: [380, 480, 760, 1160, 1482],
  },
};

const WEBP = '.webp';

/** `<slug>.webp` at the largest width, `<slug>-{w}.webp` at every other. */
export function storePhotoSrc(entry: StorePhoto, width: number): string {
  if (width === entry.width) return entry.photo;
  return `${entry.photo.slice(0, -WEBP.length)}-${width}${WEBP}`;
}

/** The full `srcset` value for one photo's own renditions. */
export function storePhotoSrcSet(entry: StorePhoto): string {
  return entry.widths.map((w) => `${storePhotoSrc(entry, w)} ${w}w`).join(', ');
}
