// Generated by scripts/gen-taxonomy-ids.mjs from docs/build/taxonomy-ids.json.
// Do not edit by hand: run `node scripts/gen-taxonomy-ids.mjs` after a store
// write instead.
//
// 0 taxonomy slug(s) resolved to a live Salla category id.
// Empty until batch S5 runs `salla-categories.mjs --apply`: until then every
// taxonomy link resolves through the live category list or the search
// fallback instead (app/components/listing/useTaxonomyLinks.ts).

export const TAXONOMY_IDS: Record<string, number> = {

};
