/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteImport } from './../node_modules/.pnpm/@salla.sa+twilight-theme-en_0d498908f52b85eb67136089d73316ea/node_modules/@salla.sa/twilight-theme-engine/.twilight/$locale'
import { Route as indexRouteImport } from './routes/index'
import { Route as DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteImport } from './../node_modules/.pnpm/@salla.sa+twilight-theme-en_0d498908f52b85eb67136089d73316ea/node_modules/@salla.sa/twilight-theme-engine/.twilight/account'
import { Route as blogRouteImport } from './routes/blog'
import { Route as brandsRouteImport } from './routes/brands'
import { Route as cartRouteImport } from './routes/cart'
import { Route as kitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as latestProductsRouteImport } from './routes/latest-products'
import { Route as loyaltyRouteImport } from './routes/loyalty'
import { Route as mostSalesProductsRouteImport } from './routes/most-sales-products'
import { Route as offersRouteImport } from './routes/offers'
import { Route as pendingOrdersRouteImport } from './routes/pending-orders'
import { Route as searchRouteImport } from './routes/search'
import { Route as testimonialsRouteImport } from './routes/testimonials'
import { Route as slugDotbrandIdRouteImport } from './routes/$slug.brand-$id'
import { Route as slugDotcidRouteImport } from './routes/$slug.c$id'
import { Route as slugDotpageIdRouteImport } from './routes/$slug.page-$id'
import { Route as slugDotpidRouteImport } from './routes/$slug.p$id'
import { Route as slugDottagIdRouteImport } from './routes/$slug.tag-$id'
import { Route as accountDotnotificationsRouteImport } from './routes/account.notifications'
import { Route as accountDotordersRouteImport } from './routes/account.orders'
import { Route as accountDotprofileRouteImport } from './routes/account.profile'
import { Route as accountDotsettingsRouteImport } from './routes/account.settings'
import { Route as accountDotwalletRouteImport } from './routes/account.wallet'
import { Route as accountDotwishlistRouteImport } from './routes/account.wishlist'
import { Route as brandsDotidRouteImport } from './routes/brands.$id'
import { Route as tagsDotidRouteImport } from './routes/tags.$id'
import { Route as thankyouDotorderIdRouteImport } from './routes/thankyou.$orderId'
import { Route as accountDotordersDotidRouteImport } from './routes/account.orders.$id'
import { Route as blog_DotslugDotaIdRouteImport } from './routes/blog_.$slug.a-$id'
import { Route as blog_DotslugDotcIdRouteImport } from './routes/blog_.$slug.c-$id'
import { Route as blog_DotslugDottagIdRouteImport } from './routes/blog_.$slug.tag-$id'
import { Route as blog_DotauthorDotidRouteImport } from './routes/blog_.author.$id'
import { Route as DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRouteImport } from './../node_modules/.pnpm/@salla.sa+twilight-theme-en_0d498908f52b85eb67136089d73316ea/node_modules/@salla.sa/twilight-theme-engine/.twilight/redirect.$type.$id'

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteImport.update(
    {
      id: '/{-$locale}',
      path: '/{-$locale}',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteImport.update(
    {
      id: '/account',
      path: '/account',
      getParentRoute: () =>
        DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
    } as any,
  )
const blogRoute = blogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const brandsRoute = brandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const cartRoute = cartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const kitchenSinkRoute = kitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const latestProductsRoute = latestProductsRouteImport.update({
  id: '/latest-products',
  path: '/latest-products',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const loyaltyRoute = loyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const mostSalesProductsRoute = mostSalesProductsRouteImport.update({
  id: '/most-sales-products',
  path: '/most-sales-products',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const offersRoute = offersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const pendingOrdersRoute = pendingOrdersRouteImport.update({
  id: '/pending-orders',
  path: '/pending-orders',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const searchRoute = searchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const testimonialsRoute = testimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const slugDotbrandIdRoute = slugDotbrandIdRouteImport.update({
  id: '/$slug/brand-{$id}',
  path: '/$slug/brand-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const slugDotcidRoute = slugDotcidRouteImport.update({
  id: '/$slug/c{$id}',
  path: '/$slug/c{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const slugDotpageIdRoute = slugDotpageIdRouteImport.update({
  id: '/$slug/page-{$id}',
  path: '/$slug/page-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const slugDotpidRoute = slugDotpidRouteImport.update({
  id: '/$slug/p{$id}',
  path: '/$slug/p{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const slugDottagIdRoute = slugDottagIdRouteImport.update({
  id: '/$slug/tag-{$id}',
  path: '/$slug/tag-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const accountDotnotificationsRoute = accountDotnotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotordersRoute = accountDotordersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotprofileRoute = accountDotprofileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotsettingsRoute = accountDotsettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotwalletRoute = accountDotwalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const accountDotwishlistRoute = accountDotwishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const brandsDotidRoute = brandsDotidRouteImport.update({
  id: '/brands/$id',
  path: '/brands/$id',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const tagsDotidRoute = tagsDotidRouteImport.update({
  id: '/tags/$id',
  path: '/tags/$id',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const thankyouDotorderIdRoute = thankyouDotorderIdRouteImport.update({
  id: '/thankyou/$orderId',
  path: '/thankyou/$orderId',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const accountDotordersDotidRoute = accountDotordersDotidRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute,
} as any)
const blog_DotslugDotaIdRoute = blog_DotslugDotaIdRouteImport.update({
  id: '/blog/$slug/a-{$id}',
  path: '/blog/$slug/a-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const blog_DotslugDotcIdRoute = blog_DotslugDotcIdRouteImport.update({
  id: '/blog/$slug/c-{$id}',
  path: '/blog/$slug/c-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const blog_DotslugDottagIdRoute = blog_DotslugDottagIdRouteImport.update({
  id: '/blog/$slug/tag-{$id}',
  path: '/blog/$slug/tag-{$id}',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const blog_DotauthorDotidRoute = blog_DotauthorDotidRouteImport.update({
  id: '/blog/author/$id',
  path: '/blog/author/$id',
  getParentRoute: () =>
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
} as any)
const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRouteImport.update(
    {
      id: '/redirect/$type/$id',
      path: '/redirect/$type/$id',
      getParentRoute: () =>
        DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren
  '/{-$locale}/': typeof indexRoute
  '/{-$locale}/account': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren
  '/{-$locale}/blog': typeof blogRoute
  '/{-$locale}/brands': typeof brandsRoute
  '/{-$locale}/cart': typeof cartRoute
  '/{-$locale}/kitchen-sink': typeof kitchenSinkRoute
  '/{-$locale}/latest-products': typeof latestProductsRoute
  '/{-$locale}/loyalty': typeof loyaltyRoute
  '/{-$locale}/most-sales-products': typeof mostSalesProductsRoute
  '/{-$locale}/offers': typeof offersRoute
  '/{-$locale}/pending-orders': typeof pendingOrdersRoute
  '/{-$locale}/search': typeof searchRoute
  '/{-$locale}/testimonials': typeof testimonialsRoute
  '/{-$locale}/$slug/brand-{$id}': typeof slugDotbrandIdRoute
  '/{-$locale}/$slug/c{$id}': typeof slugDotcidRoute
  '/{-$locale}/$slug/page-{$id}': typeof slugDotpageIdRoute
  '/{-$locale}/$slug/p{$id}': typeof slugDotpidRoute
  '/{-$locale}/$slug/tag-{$id}': typeof slugDottagIdRoute
  '/{-$locale}/account/notifications': typeof accountDotnotificationsRoute
  '/{-$locale}/account/orders': typeof accountDotordersRoute
  '/{-$locale}/account/profile': typeof accountDotprofileRoute
  '/{-$locale}/account/settings': typeof accountDotsettingsRoute
  '/{-$locale}/account/wallet': typeof accountDotwalletRoute
  '/{-$locale}/account/wishlist': typeof accountDotwishlistRoute
  '/{-$locale}/brands/$id': typeof brandsDotidRoute
  '/{-$locale}/tags/$id': typeof tagsDotidRoute
  '/{-$locale}/thankyou/$orderId': typeof thankyouDotorderIdRoute
  '/{-$locale}/account/orders/$id': typeof accountDotordersDotidRoute
  '/{-$locale}/blog/$slug/a-{$id}': typeof blog_DotslugDotaIdRoute
  '/{-$locale}/blog/$slug/c-{$id}': typeof blog_DotslugDotcIdRoute
  '/{-$locale}/blog/$slug/tag-{$id}': typeof blog_DotslugDottagIdRoute
  '/{-$locale}/blog/author/$id': typeof blog_DotauthorDotidRoute
  '/{-$locale}/redirect/$type/$id': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof indexRoute
  '/{-$locale}/account': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren
  '/{-$locale}/blog': typeof blogRoute
  '/{-$locale}/brands': typeof brandsRoute
  '/{-$locale}/cart': typeof cartRoute
  '/{-$locale}/kitchen-sink': typeof kitchenSinkRoute
  '/{-$locale}/latest-products': typeof latestProductsRoute
  '/{-$locale}/loyalty': typeof loyaltyRoute
  '/{-$locale}/most-sales-products': typeof mostSalesProductsRoute
  '/{-$locale}/offers': typeof offersRoute
  '/{-$locale}/pending-orders': typeof pendingOrdersRoute
  '/{-$locale}/search': typeof searchRoute
  '/{-$locale}/testimonials': typeof testimonialsRoute
  '/{-$locale}/$slug/brand-{$id}': typeof slugDotbrandIdRoute
  '/{-$locale}/$slug/c{$id}': typeof slugDotcidRoute
  '/{-$locale}/$slug/page-{$id}': typeof slugDotpageIdRoute
  '/{-$locale}/$slug/p{$id}': typeof slugDotpidRoute
  '/{-$locale}/$slug/tag-{$id}': typeof slugDottagIdRoute
  '/{-$locale}/account/notifications': typeof accountDotnotificationsRoute
  '/{-$locale}/account/orders': typeof accountDotordersRoute
  '/{-$locale}/account/profile': typeof accountDotprofileRoute
  '/{-$locale}/account/settings': typeof accountDotsettingsRoute
  '/{-$locale}/account/wallet': typeof accountDotwalletRoute
  '/{-$locale}/account/wishlist': typeof accountDotwishlistRoute
  '/{-$locale}/brands/$id': typeof brandsDotidRoute
  '/{-$locale}/tags/$id': typeof tagsDotidRoute
  '/{-$locale}/thankyou/$orderId': typeof thankyouDotorderIdRoute
  '/{-$locale}/account/orders/$id': typeof accountDotordersDotidRoute
  '/{-$locale}/blog/$slug/a-{$id}': typeof blog_DotslugDotaIdRoute
  '/{-$locale}/blog/$slug/c-{$id}': typeof blog_DotslugDotcIdRoute
  '/{-$locale}/blog/$slug/tag-{$id}': typeof blog_DotslugDottagIdRoute
  '/{-$locale}/blog/author/$id': typeof blog_DotauthorDotidRoute
  '/{-$locale}/redirect/$type/$id': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren
  '/{-$locale}/': typeof indexRoute
  '/{-$locale}/account': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren
  '/{-$locale}/blog': typeof blogRoute
  '/{-$locale}/brands': typeof brandsRoute
  '/{-$locale}/cart': typeof cartRoute
  '/{-$locale}/kitchen-sink': typeof kitchenSinkRoute
  '/{-$locale}/latest-products': typeof latestProductsRoute
  '/{-$locale}/loyalty': typeof loyaltyRoute
  '/{-$locale}/most-sales-products': typeof mostSalesProductsRoute
  '/{-$locale}/offers': typeof offersRoute
  '/{-$locale}/pending-orders': typeof pendingOrdersRoute
  '/{-$locale}/search': typeof searchRoute
  '/{-$locale}/testimonials': typeof testimonialsRoute
  '/{-$locale}/$slug/brand-{$id}': typeof slugDotbrandIdRoute
  '/{-$locale}/$slug/c{$id}': typeof slugDotcidRoute
  '/{-$locale}/$slug/page-{$id}': typeof slugDotpageIdRoute
  '/{-$locale}/$slug/p{$id}': typeof slugDotpidRoute
  '/{-$locale}/$slug/tag-{$id}': typeof slugDottagIdRoute
  '/{-$locale}/account/notifications': typeof accountDotnotificationsRoute
  '/{-$locale}/account/orders': typeof accountDotordersRoute
  '/{-$locale}/account/profile': typeof accountDotprofileRoute
  '/{-$locale}/account/settings': typeof accountDotsettingsRoute
  '/{-$locale}/account/wallet': typeof accountDotwalletRoute
  '/{-$locale}/account/wishlist': typeof accountDotwishlistRoute
  '/{-$locale}/brands/$id': typeof brandsDotidRoute
  '/{-$locale}/tags/$id': typeof tagsDotidRoute
  '/{-$locale}/thankyou/$orderId': typeof thankyouDotorderIdRoute
  '/{-$locale}/account/orders/$id': typeof accountDotordersDotidRoute
  '/{-$locale}/blog/$slug/a-{$id}': typeof blog_DotslugDotaIdRoute
  '/{-$locale}/blog/$slug/c-{$id}': typeof blog_DotslugDotcIdRoute
  '/{-$locale}/blog/$slug/tag-{$id}': typeof blog_DotslugDottagIdRoute
  '/{-$locale}/blog/author/$id': typeof blog_DotauthorDotidRoute
  '/{-$locale}/redirect/$type/$id': typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/account'
    | '/{-$locale}/blog'
    | '/{-$locale}/brands'
    | '/{-$locale}/cart'
    | '/{-$locale}/kitchen-sink'
    | '/{-$locale}/latest-products'
    | '/{-$locale}/loyalty'
    | '/{-$locale}/most-sales-products'
    | '/{-$locale}/offers'
    | '/{-$locale}/pending-orders'
    | '/{-$locale}/search'
    | '/{-$locale}/testimonials'
    | '/{-$locale}/$slug/brand-{$id}'
    | '/{-$locale}/$slug/c{$id}'
    | '/{-$locale}/$slug/page-{$id}'
    | '/{-$locale}/$slug/p{$id}'
    | '/{-$locale}/$slug/tag-{$id}'
    | '/{-$locale}/account/notifications'
    | '/{-$locale}/account/orders'
    | '/{-$locale}/account/profile'
    | '/{-$locale}/account/settings'
    | '/{-$locale}/account/wallet'
    | '/{-$locale}/account/wishlist'
    | '/{-$locale}/brands/$id'
    | '/{-$locale}/tags/$id'
    | '/{-$locale}/thankyou/$orderId'
    | '/{-$locale}/account/orders/$id'
    | '/{-$locale}/blog/$slug/a-{$id}'
    | '/{-$locale}/blog/$slug/c-{$id}'
    | '/{-$locale}/blog/$slug/tag-{$id}'
    | '/{-$locale}/blog/author/$id'
    | '/{-$locale}/redirect/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{-$locale}/account'
    | '/{-$locale}/blog'
    | '/{-$locale}/brands'
    | '/{-$locale}/cart'
    | '/{-$locale}/kitchen-sink'
    | '/{-$locale}/latest-products'
    | '/{-$locale}/loyalty'
    | '/{-$locale}/most-sales-products'
    | '/{-$locale}/offers'
    | '/{-$locale}/pending-orders'
    | '/{-$locale}/search'
    | '/{-$locale}/testimonials'
    | '/{-$locale}/$slug/brand-{$id}'
    | '/{-$locale}/$slug/c{$id}'
    | '/{-$locale}/$slug/page-{$id}'
    | '/{-$locale}/$slug/p{$id}'
    | '/{-$locale}/$slug/tag-{$id}'
    | '/{-$locale}/account/notifications'
    | '/{-$locale}/account/orders'
    | '/{-$locale}/account/profile'
    | '/{-$locale}/account/settings'
    | '/{-$locale}/account/wallet'
    | '/{-$locale}/account/wishlist'
    | '/{-$locale}/brands/$id'
    | '/{-$locale}/tags/$id'
    | '/{-$locale}/thankyou/$orderId'
    | '/{-$locale}/account/orders/$id'
    | '/{-$locale}/blog/$slug/a-{$id}'
    | '/{-$locale}/blog/$slug/c-{$id}'
    | '/{-$locale}/blog/$slug/tag-{$id}'
    | '/{-$locale}/blog/author/$id'
    | '/{-$locale}/redirect/$type/$id'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/account'
    | '/{-$locale}/blog'
    | '/{-$locale}/brands'
    | '/{-$locale}/cart'
    | '/{-$locale}/kitchen-sink'
    | '/{-$locale}/latest-products'
    | '/{-$locale}/loyalty'
    | '/{-$locale}/most-sales-products'
    | '/{-$locale}/offers'
    | '/{-$locale}/pending-orders'
    | '/{-$locale}/search'
    | '/{-$locale}/testimonials'
    | '/{-$locale}/$slug/brand-{$id}'
    | '/{-$locale}/$slug/c{$id}'
    | '/{-$locale}/$slug/page-{$id}'
    | '/{-$locale}/$slug/p{$id}'
    | '/{-$locale}/$slug/tag-{$id}'
    | '/{-$locale}/account/notifications'
    | '/{-$locale}/account/orders'
    | '/{-$locale}/account/profile'
    | '/{-$locale}/account/settings'
    | '/{-$locale}/account/wallet'
    | '/{-$locale}/account/wishlist'
    | '/{-$locale}/brands/$id'
    | '/{-$locale}/tags/$id'
    | '/{-$locale}/thankyou/$orderId'
    | '/{-$locale}/account/orders/$id'
    | '/{-$locale}/blog/$slug/a-{$id}'
    | '/{-$locale}/blog/$slug/c-{$id}'
    | '/{-$locale}/blog/$slug/tag-{$id}'
    | '/{-$locale}/blog/author/$id'
    | '/{-$locale}/redirect/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/account': {
      id: '/{-$locale}/account'
      path: '/account'
      fullPath: '/{-$locale}/account'
      preLoaderRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/blog': {
      id: '/{-$locale}/blog'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof blogRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/brands': {
      id: '/{-$locale}/brands'
      path: '/brands'
      fullPath: '/{-$locale}/brands'
      preLoaderRoute: typeof brandsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/cart': {
      id: '/{-$locale}/cart'
      path: '/cart'
      fullPath: '/{-$locale}/cart'
      preLoaderRoute: typeof cartRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/kitchen-sink': {
      id: '/{-$locale}/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/{-$locale}/kitchen-sink'
      preLoaderRoute: typeof kitchenSinkRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/latest-products': {
      id: '/{-$locale}/latest-products'
      path: '/latest-products'
      fullPath: '/{-$locale}/latest-products'
      preLoaderRoute: typeof latestProductsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/loyalty': {
      id: '/{-$locale}/loyalty'
      path: '/loyalty'
      fullPath: '/{-$locale}/loyalty'
      preLoaderRoute: typeof loyaltyRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/most-sales-products': {
      id: '/{-$locale}/most-sales-products'
      path: '/most-sales-products'
      fullPath: '/{-$locale}/most-sales-products'
      preLoaderRoute: typeof mostSalesProductsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/offers': {
      id: '/{-$locale}/offers'
      path: '/offers'
      fullPath: '/{-$locale}/offers'
      preLoaderRoute: typeof offersRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/pending-orders': {
      id: '/{-$locale}/pending-orders'
      path: '/pending-orders'
      fullPath: '/{-$locale}/pending-orders'
      preLoaderRoute: typeof pendingOrdersRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/search': {
      id: '/{-$locale}/search'
      path: '/search'
      fullPath: '/{-$locale}/search'
      preLoaderRoute: typeof searchRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/testimonials': {
      id: '/{-$locale}/testimonials'
      path: '/testimonials'
      fullPath: '/{-$locale}/testimonials'
      preLoaderRoute: typeof testimonialsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/brand-{$id}': {
      id: '/{-$locale}/$slug/brand-{$id}'
      path: '/$slug/brand-{$id}'
      fullPath: '/{-$locale}/$slug/brand-{$id}'
      preLoaderRoute: typeof slugDotbrandIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/c{$id}': {
      id: '/{-$locale}/$slug/c{$id}'
      path: '/$slug/c{$id}'
      fullPath: '/{-$locale}/$slug/c{$id}'
      preLoaderRoute: typeof slugDotcidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/page-{$id}': {
      id: '/{-$locale}/$slug/page-{$id}'
      path: '/$slug/page-{$id}'
      fullPath: '/{-$locale}/$slug/page-{$id}'
      preLoaderRoute: typeof slugDotpageIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/p{$id}': {
      id: '/{-$locale}/$slug/p{$id}'
      path: '/$slug/p{$id}'
      fullPath: '/{-$locale}/$slug/p{$id}'
      preLoaderRoute: typeof slugDotpidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/$slug/tag-{$id}': {
      id: '/{-$locale}/$slug/tag-{$id}'
      path: '/$slug/tag-{$id}'
      fullPath: '/{-$locale}/$slug/tag-{$id}'
      preLoaderRoute: typeof slugDottagIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/account/notifications': {
      id: '/{-$locale}/account/notifications'
      path: '/notifications'
      fullPath: '/{-$locale}/account/notifications'
      preLoaderRoute: typeof accountDotnotificationsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/orders': {
      id: '/{-$locale}/account/orders'
      path: '/orders'
      fullPath: '/{-$locale}/account/orders'
      preLoaderRoute: typeof accountDotordersRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/profile': {
      id: '/{-$locale}/account/profile'
      path: '/profile'
      fullPath: '/{-$locale}/account/profile'
      preLoaderRoute: typeof accountDotprofileRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/settings': {
      id: '/{-$locale}/account/settings'
      path: '/settings'
      fullPath: '/{-$locale}/account/settings'
      preLoaderRoute: typeof accountDotsettingsRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/wallet': {
      id: '/{-$locale}/account/wallet'
      path: '/wallet'
      fullPath: '/{-$locale}/account/wallet'
      preLoaderRoute: typeof accountDotwalletRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/account/wishlist': {
      id: '/{-$locale}/account/wishlist'
      path: '/wishlist'
      fullPath: '/{-$locale}/account/wishlist'
      preLoaderRoute: typeof accountDotwishlistRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/brands/$id': {
      id: '/{-$locale}/brands/$id'
      path: '/brands/$id'
      fullPath: '/{-$locale}/brands/$id'
      preLoaderRoute: typeof brandsDotidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/tags/$id': {
      id: '/{-$locale}/tags/$id'
      path: '/tags/$id'
      fullPath: '/{-$locale}/tags/$id'
      preLoaderRoute: typeof tagsDotidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/thankyou/$orderId': {
      id: '/{-$locale}/thankyou/$orderId'
      path: '/thankyou/$orderId'
      fullPath: '/{-$locale}/thankyou/$orderId'
      preLoaderRoute: typeof thankyouDotorderIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/account/orders/$id': {
      id: '/{-$locale}/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/{-$locale}/account/orders/$id'
      preLoaderRoute: typeof accountDotordersDotidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute
    }
    '/{-$locale}/blog/$slug/a-{$id}': {
      id: '/{-$locale}/blog/$slug/a-{$id}'
      path: '/blog/$slug/a-{$id}'
      fullPath: '/{-$locale}/blog/$slug/a-{$id}'
      preLoaderRoute: typeof blog_DotslugDotaIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/blog/$slug/c-{$id}': {
      id: '/{-$locale}/blog/$slug/c-{$id}'
      path: '/blog/$slug/c-{$id}'
      fullPath: '/{-$locale}/blog/$slug/c-{$id}'
      preLoaderRoute: typeof blog_DotslugDotcIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/blog/$slug/tag-{$id}': {
      id: '/{-$locale}/blog/$slug/tag-{$id}'
      path: '/blog/$slug/tag-{$id}'
      fullPath: '/{-$locale}/blog/$slug/tag-{$id}'
      preLoaderRoute: typeof blog_DotslugDottagIdRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/blog/author/$id': {
      id: '/{-$locale}/blog/author/$id'
      path: '/blog/author/$id'
      fullPath: '/{-$locale}/blog/author/$id'
      preLoaderRoute: typeof blog_DotauthorDotidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
    '/{-$locale}/redirect/$type/$id': {
      id: '/{-$locale}/redirect/$type/$id'
      path: '/redirect/$type/$id'
      fullPath: '/{-$locale}/redirect/$type/$id'
      preLoaderRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRouteImport
      parentRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute
    }
  }
}

interface DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteChildren {
  accountDotnotificationsRoute: typeof accountDotnotificationsRoute
  accountDotordersRoute: typeof accountDotordersRoute
  accountDotprofileRoute: typeof accountDotprofileRoute
  accountDotsettingsRoute: typeof accountDotsettingsRoute
  accountDotwalletRoute: typeof accountDotwalletRoute
  accountDotwishlistRoute: typeof accountDotwishlistRoute
  accountDotordersDotidRoute: typeof accountDotordersDotidRoute
}

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteChildren: DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteChildren =
  {
    accountDotnotificationsRoute: accountDotnotificationsRoute,
    accountDotordersRoute: accountDotordersRoute,
    accountDotprofileRoute: accountDotprofileRoute,
    accountDotsettingsRoute: accountDotsettingsRoute,
    accountDotwalletRoute: accountDotwalletRoute,
    accountDotwishlistRoute: accountDotwishlistRoute,
    accountDotordersDotidRoute: accountDotordersDotidRoute,
  }

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute._addFileChildren(
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteChildren,
  )

interface DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteChildren {
  indexRoute: typeof indexRoute
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren
  blogRoute: typeof blogRoute
  brandsRoute: typeof brandsRoute
  cartRoute: typeof cartRoute
  kitchenSinkRoute: typeof kitchenSinkRoute
  latestProductsRoute: typeof latestProductsRoute
  loyaltyRoute: typeof loyaltyRoute
  mostSalesProductsRoute: typeof mostSalesProductsRoute
  offersRoute: typeof offersRoute
  pendingOrdersRoute: typeof pendingOrdersRoute
  searchRoute: typeof searchRoute
  testimonialsRoute: typeof testimonialsRoute
  slugDotbrandIdRoute: typeof slugDotbrandIdRoute
  slugDotcidRoute: typeof slugDotcidRoute
  slugDotpageIdRoute: typeof slugDotpageIdRoute
  slugDotpidRoute: typeof slugDotpidRoute
  slugDottagIdRoute: typeof slugDottagIdRoute
  brandsDotidRoute: typeof brandsDotidRoute
  tagsDotidRoute: typeof tagsDotidRoute
  thankyouDotorderIdRoute: typeof thankyouDotorderIdRoute
  blog_DotslugDotaIdRoute: typeof blog_DotslugDotaIdRoute
  blog_DotslugDotcIdRoute: typeof blog_DotslugDotcIdRoute
  blog_DotslugDottagIdRoute: typeof blog_DotslugDottagIdRoute
  blog_DotauthorDotidRoute: typeof blog_DotauthorDotidRoute
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute: typeof DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute
}

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteChildren: DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteChildren =
  {
    indexRoute: indexRoute,
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRoute:
      DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightAccountRouteWithChildren,
    blogRoute: blogRoute,
    brandsRoute: brandsRoute,
    cartRoute: cartRoute,
    kitchenSinkRoute: kitchenSinkRoute,
    latestProductsRoute: latestProductsRoute,
    loyaltyRoute: loyaltyRoute,
    mostSalesProductsRoute: mostSalesProductsRoute,
    offersRoute: offersRoute,
    pendingOrdersRoute: pendingOrdersRoute,
    searchRoute: searchRoute,
    testimonialsRoute: testimonialsRoute,
    slugDotbrandIdRoute: slugDotbrandIdRoute,
    slugDotcidRoute: slugDotcidRoute,
    slugDotpageIdRoute: slugDotpageIdRoute,
    slugDotpidRoute: slugDotpidRoute,
    slugDottagIdRoute: slugDottagIdRoute,
    brandsDotidRoute: brandsDotidRoute,
    tagsDotidRoute: tagsDotidRoute,
    thankyouDotorderIdRoute: thankyouDotorderIdRoute,
    blog_DotslugDotaIdRoute: blog_DotslugDotaIdRoute,
    blog_DotslugDotcIdRoute: blog_DotslugDotcIdRoute,
    blog_DotslugDottagIdRoute: blog_DotslugDottagIdRoute,
    blog_DotauthorDotidRoute: blog_DotauthorDotidRoute,
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute:
      DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightRedirectDottypeDotidRoute,
  }

const DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren =
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute._addFileChildren(
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRoute:
    DotDotDotDotNode_modulesDotpnpmAtsallaDotsaChar43twilightThemeEn_0d498908f52b85eb67136089d73316eaNode_modulesAtsallaDotsaTwilightThemeEngineDottwilightLocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
